// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { ConnectDisconnectData, ConnectDisconnectResponse, ConnectGetConnectData, ConnectGetConnectResponse, ConnectConnectData, ConnectConnectResponse, ConnectConnectError, CountsCountsData, CountsCountsError, FlowsFlowsData, FlowsFlowsError, MapGetMapData, MapGetMapResponse, DisconnectGodownData, DisconnectGodownResponse, DisconnectGodownError, HomeData, HomeResponse, ReconnectReconnectData, ReconnectReconnectError, UpdateUpdateData, UpdateUpdateResponse, UpdateUpdateError } from './types.gen';

export const client = createClient(createConfig());

/**
 * Disconnect
 */
export const connectDisconnect = <ThrowOnError extends boolean = false>(options?: Options<ConnectDisconnectData, ThrowOnError>) => {
    return (options?.client ?? client).delete<ConnectDisconnectResponse, unknown, ThrowOnError>({
        url: '/connect',
        ...options
    });
};

/**
 * Connect (preview)
 * Registry nodes data.
 */
export const connectGetConnect = <ThrowOnError extends boolean = false>(options?: Options<ConnectGetConnectData, ThrowOnError>) => {
    return (options?.client ?? client).get<ConnectGetConnectResponse, unknown, ThrowOnError>({
        url: '/connect',
        ...options
    });
};

/**
 * Connect
 * Connect to registry as node/registry.
 */
export const connectConnect = <ThrowOnError extends boolean = false>(options: Options<ConnectConnectData, ThrowOnError>) => {
    return (options?.client ?? client).post<ConnectConnectResponse, ConnectConnectError, ThrowOnError>({
        url: '/connect',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Counts
 */
export const countsCounts = <ThrowOnError extends boolean = false>(options?: Options<CountsCountsData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, CountsCountsError, ThrowOnError>({
        url: '/counts',
        ...options
    });
};

/**
 * Flows
 */
export const flowsFlows = <ThrowOnError extends boolean = false>(options?: Options<FlowsFlowsData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, FlowsFlowsError, ThrowOnError>({
        url: '/flows',
        ...options
    });
};

/**
 * Map
 * Runtime data on providers, connection and registers.
 */
export const mapGetMap = <ThrowOnError extends boolean = false>(options?: Options<MapGetMapData, ThrowOnError>) => {
    return (options?.client ?? client).get<MapGetMapResponse, unknown, ThrowOnError>({
        url: '/map',
        ...options
    });
};

/**
 * Godown
 */
export const disconnectGodown = <ThrowOnError extends boolean = false>(options: Options<DisconnectGodownData, ThrowOnError>) => {
    return (options?.client ?? client).post<DisconnectGodownResponse, DisconnectGodownError, ThrowOnError>({
        url: '/disconnect',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Home
 * Genearl state information of the registry/node.
 */
export const home = <ThrowOnError extends boolean = false>(options?: Options<HomeData, ThrowOnError>) => {
    return (options?.client ?? client).get<HomeResponse, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Reconnect
 */
export const reconnectReconnect = <ThrowOnError extends boolean = false>(options: Options<ReconnectReconnectData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, ReconnectReconnectError, ThrowOnError>({
        url: '/reconnect',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update
 */
export const updateUpdate = <ThrowOnError extends boolean = false>(options: Options<UpdateUpdateData, ThrowOnError>) => {
    return (options?.client ?? client).post<UpdateUpdateResponse, UpdateUpdateError, ThrowOnError>({
        url: '/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};