// This file is auto-generated by @hey-api/openapi-ts

export type Connect = {
    url: string;
    organization?: string | null;
    registry: boolean;
    feed: boolean;
    idle: boolean;
    now: string;
    message: Array<string>;
    nodes: Array<Node>;
};

export type DefaultResponse = {
    url: string;
    organization?: string | null;
    registry: boolean;
    feed: boolean;
    idle: boolean;
    now: string;
    message: Array<string>;
};

export type Disconnect = {
    provider: string;
    url: Array<string>;
};

export type Flow = {
    url: string;
    name: string;
    description?: string | null;
    author?: string | null;
    tags?: Array<string> | null;
};

export type Node = {
    url: string;
    organization?: string | null;
    flows: Array<Flow>;
    created?: string | null;
    modified?: string | null;
    heartbeat?: string | null;
    status?: string | null;
};

export type Provider = {
    url: string;
    organization?: string | null;
    feed: boolean;
    created?: string | null;
    modified?: string | null;
    nodes: Array<Node>;
};

export type ProviderMap = {
    url: string;
    organization?: string | null;
    registry: boolean;
    feed: boolean;
    idle: boolean;
    now: string;
    message: Array<string>;
    providers: Array<Provider>;
    connection: {
        [key: string]: string | null;
    };
    registers: {
        [key: string]: string;
    };
};

export type ConnectDisconnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect';
};

export type ConnectDisconnectResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ConnectDisconnectResponse = ConnectDisconnectResponses[keyof ConnectDisconnectResponses];

export type ConnectGetConnectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/connect';
};

export type ConnectGetConnectResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Connect;
};

export type ConnectGetConnectResponse = ConnectGetConnectResponses[keyof ConnectGetConnectResponses];

export type ConnectConnectData = {
    body: Connect;
    path?: never;
    query?: never;
    url: '/connect';
};

export type ConnectConnectErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ConnectConnectError = ConnectConnectErrors[keyof ConnectConnectErrors];

export type ConnectConnectResponses = {
    /**
     * Document created, URL follows
     */
    201: Connect | DefaultResponse;
};

export type ConnectConnectResponse = ConnectConnectResponses[keyof ConnectConnectResponses];

export type CountsCountsData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'html' | null;
    };
    url: '/counts';
};

export type CountsCountsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type CountsCountsError = CountsCountsErrors[keyof CountsCountsErrors];

export type CountsCountsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type FlowsFlowsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string | null;
        by?: string | null;
        pp?: number;
        p?: number;
        format?: 'json' | 'html' | null;
    };
    url: '/flows';
};

export type FlowsFlowsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type FlowsFlowsError = FlowsFlowsErrors[keyof FlowsFlowsErrors];

export type FlowsFlowsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: unknown;
};

export type MapGetMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/map';
};

export type MapGetMapResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: ProviderMap;
};

export type MapGetMapResponse = MapGetMapResponses[keyof MapGetMapResponses];

export type DisconnectGodownData = {
    body: Disconnect;
    path?: never;
    query?: never;
    url: '/disconnect';
};

export type DisconnectGodownErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type DisconnectGodownError = DisconnectGodownErrors[keyof DisconnectGodownErrors];

export type DisconnectGodownResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: unknown;
    };
};

export type DisconnectGodownResponse = DisconnectGodownResponses[keyof DisconnectGodownResponses];

export type HomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HomeResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: DefaultResponse;
};

export type HomeResponse = HomeResponses[keyof HomeResponses];

export type ReconnectReconnectData = {
    body: DefaultResponse;
    path?: never;
    query?: never;
    url: '/reconnect';
};

export type ReconnectReconnectErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type ReconnectReconnectError = ReconnectReconnectErrors[keyof ReconnectReconnectErrors];

export type ReconnectReconnectResponses = {
    /**
     * Document created, URL follows
     */
    201: unknown;
};

export type UpdateUpdateData = {
    body: Connect;
    path?: never;
    query?: never;
    url: '/update';
};

export type UpdateUpdateErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | Array<unknown> | Array<unknown>;
    };
};

export type UpdateUpdateError = UpdateUpdateErrors[keyof UpdateUpdateErrors];

export type UpdateUpdateResponses = {
    /**
     * Document created, URL follows
     */
    201: DefaultResponse;
};

export type UpdateUpdateResponse = UpdateUpdateResponses[keyof UpdateUpdateResponses];